[package]
name = "xcontent"
version = "0.1.0"
edition = "2021"

[dependencies]
sha-1 = "0.10.0"
vfs = "0.12"

thiserror = "1.0"
chrono = { version = "0.4", features = ["serde", "wasmbind"] }
serde = { version = "1.0", features = ["derive", "rc"] }
binrw = "0.13"
variantly = "0.4"
stfs = { path = "../stfs" }
xecrypt = { path = "../xecrypt", features = ["serde"] }
