[package]
name = "blf_lib-derivable"
description = "Shared traits used by blf_lib and blf_lib-derive"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
binrw = "0.14.1"
serde_json = "1.0.140"
csv = "1.3.1"