[package]
name = "blf_lib-derive"
description = "Derive macros for blf_lib"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.79"
quote = "1.0.37"
indoc = "2.0.5"
bincode = "2.0.0-rc.3"
virtue = "0.0.17"
proc-macro2 = "1.0.86"