[package]
name = "blf_lib-derive"
description = "Derive macros for blf_lib"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.79"
quote = "1.0.37"
indoc = "2.0.5"
proc-macro2 = "1.0.86"
blf_lib-derivable = { path = '../blf_lib-derivable' }