[package]
name = "stfs"
version = "0.1.0"
edition = "2021"

[dependencies]
vfs = "0.12"

thiserror = "1.0"
chrono = { version = "0.4", features = ["serde", "wasmbind"] }
serde = { version = "1.0", features = ["derive", "rc"] }
binrw = "0.13"
variantly = "0.4"
parking_lot = { version = "0.12", features = ["serde"] }
modular-bitfield = "0.11"
sha1 = "0.10"

[patch.crates-io]
