name: blf_lib
on:
  push:
    branches: [ "main", "workflow" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main", "workflow" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_lib:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      working-directory: ./blf_lib
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./blf_lib
      run: cargo test --verbose