name: blf_lib
on:
  push:
    branches: [ "main", "workflow" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main", "workflow" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_lib:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      working-directory: ./blf_lib
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./blf_lib
      run: cargo test --verbose

  publish_lib:
    name: "Publish"
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - build_lib
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Set up cargo registry credentials
      run: |
        echo "//crates.io/api/v1/packages" >> ~/.cargo/config
        echo "username = \"${{ secrets.CARGO_USERNAME }}\"" >> ~/.cargo/config
        echo "token = \"${{ secrets.CARGO_TOKEN }}\"" >> ~/.cargo/config
    - name: Publish crate
      working-directory: ./blf_lib
      run: cargo publish --no-verify
      env:
        CARGO_USERNAME: ${{ secrets.CARGO_USERNAME }}
        CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
