name: Release
on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_wasm:
    name: "Publish blf_wasm"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build
        working-directory: /home/runner/work/blf_lib/blf_lib
        run: wasm-pack build blf_wasm --target bundler
      - name: Build
        working-directory: /home/runner/work/blf_lib/blf_lib
        run: wasm-pack publish blf_wasm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}