name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_lib:
    name: "Build blf_lib"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./blf_lib
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./blf_lib
      run: cargo test --verbose

  build_cli:
    name: "Build blf_cli"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        working-directory: ./blf_cli
        run: cargo build --verbose --release
      - name: Run tests
        working-directory: ./blf_cli
        run: cargo test --verbose
      - uses: actions/upload-artifact@v4
        with:
          path: blf_cli/target/release/blf_cli