name: Rust

on:
  push:
    branches: [ "main", "workflow", "wasm" ]
  pull_request:
    branches: [ "main", "workflow", "wasm" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_lib:
    name: "Build blf_lib"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      working-directory: ./blf_lib
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./blf_lib
      run: cargo test --verbose

  build_cli:
    name: "Build blf_cli"
    runs-on: ubuntu-latest

    steps:
      - name: Install Linux and Windows Cross Compilers
        run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32
      - name: Set up MacOS Cross Compiler
        uses: Timmmm/setup-osxcross@v2
        with:
          osx-version: "12.3"
      - name: Install Rustup targets
        run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu x86_64-apple-darwin aarch64-apple-darwin
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build
        working-directory: ./blf_cli
        run: cargo build --target x86_64-unknown-linux-musl --target x86_64-pc-windows-gnu --target x86_64-apple-darwin --target aarch64-apple-darwin --verbose --release
      - name: Run tests
        working-directory: ./blf_cli
        run: cargo test --verbose
      - name: Upload Windows Binaries
        uses: actions/upload-artifact@v4.6.1
        with:
          name: blf_cli Windows (x86_64-pc-windows-gnu)
          path: /home/runner/work/blf_lib/blf_lib/target/x86_64-pc-windows-gnu/release/blf_cli.exe
      - name: Upload Linux Binaries
        uses: actions/upload-artifact@v4.6.1
        with:
          name: blf_cli Linux (x86_64-unknown-linux-musl)
          path: /home/runner/work/blf_lib/blf_lib/target/x86_64-unknown-linux-musl/release/blf_cli
      - name: Upload MacOS Binaries (Apple Silicon)
        uses: actions/upload-artifact@v4.6.1
        with:
          name: blf_cli MacOS (aarch64-apple-darwin)
          path: /home/runner/work/blf_lib/blf_lib/target/aarch64-apple-darwin/release/blf_cli
      - name: Upload MacOS Binaries (x86)
        uses: actions/upload-artifact@v4.6.1
        with:
          name: blf_cli MacOS (x86_64-apple-darwin)
          path: /home/runner/work/blf_lib/blf_lib/target/x86_64-apple-darwin/release/blf_cli

  build_wasm:
    name: "Build blf_wasm"
    runs-on: ubuntu-latest

    steps:
      - uses: Swatinem/rust-cache@v2
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build
        working-directory: /home/runner/work/blf_lib
        run: pwd && ls -al && wasm-pack build blf_wasm --target web
      - name: Upload Wasm Package
        uses: actions/upload-artifact@v4.6.1
        with:
          name: blf_wasm
          path: /home/runner/work/blf_lib/blf_wasm/pkg